server:
  port: 9000
springdoc:
  swagger-ui:
    path: /swagger-ui.html
spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://localhost:5432/anagram
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
  sql:
    init:
      platform: postgres
  data:
    redis:
      host: localhost
      port: 6379