server:
  port: 9000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/anagram
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    platform: postgres
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create