server:
  port: 9000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/anagram
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    platform: postgres
  jpa:
    properties:
      hibernate:
        order_inserts: true
        jdbc:
          batch_size: 30
    generate-ddl: false
    hibernate:
      ddl-auto: create